# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEoX5aatHphCxJvhE_q2dYpjUC4rT95Q
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# read dataset
df = pd.read_csv("/content/creditcard.csv")

# get data dimensions
df.shape

# get the data types
df.dtypes

fig, axes = plt.subplots(5, 6, figsize=(64,48))
fig.suptitle('Box Plots of the variables')

np_df = df.to_numpy()
counter = 0
for i in range(5):
    for j in range(6):
        sns.boxplot(ax=axes[i, j], data=df.iloc[:, counter])
        axes[i, j].set_title(list(df.columns)[counter])
        counter += 1

# find the class distribution
target = df.to_numpy(dtype=np.int32)[:, -1]
# get the number of classes and the count for each class
classes, counts = np.unique(target, return_counts=True)

# identify the data percentage
for i in range(len(classes)):
    print("Class=%d, Count=%d, Percentage=%.3f%%" % (classes[i], counts[i], counts[i]*100/np.sum(counts)))

